[workspace]
resolver = "2"
members = [
    "shared",
    "registry",
    "credit-token",
    "zk-verifier",
    "marketplace",
    "retirement",
    "tests",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[workspace.dependencies]
soroban-sdk = "21"
