[package]
name = "cambium-retirement"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[features]
testutils = ["soroban-sdk/testutils"]

[dependencies]
soroban-sdk = { workspace = true }
cambium-shared = { path = "../shared" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
cambium-credit-token = { path = "../credit-token", features = ["testutils"] }
cambium-registry = { path = "../registry", features = ["testutils"] }
cambium-zk-verifier = { path = "../zk-verifier", features = ["testutils"] }
